/**
 * One-time asset prep: converts the white deck-exported SVGs in /assets into
 * brand-colored inline React components + an SVG favicon.
 *
 *   - assets/Vector-1.svg  (60x40)  -> butterfly mark
 *   - assets/Vector-2.svg  (122x28) -> full "butterfly + smalBlu" lockup
 *
 * Run: node scripts/prep-assets.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const ACCENT = "#005EFF";

function parsePaths(file) {
  const svg = readFileSync(join(root, "assets", file), "utf8");
  const viewBox = svg.match(/viewBox="([^"]+)"/)[1];
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"[^>]*\/?>(?:<\/path>)?/g)].map((m) => {
    const d = m[1];
    const start = d.match(/M\s*(-?[\d.]+)[\s,]+(-?[\d.]+)/);
    const rule = /fill-rule="evenodd"/.test(m[0]);
    return { d, x: start ? parseFloat(start[1]) : 0, evenodd: rule };
  });
  return { viewBox, paths };
}

const mark = parsePaths("Vector-1.svg");
const lockup = parsePaths("Vector-2.svg");

const markXs = mark.paths.map((p) => p.x);
const lockXs = lockup.paths.map((p) => p.x);
console.log(`Vector-1 (mark): ${mark.paths.length} paths, viewBox ${mark.viewBox}, x range ${Math.min(...markXs).toFixed(1)}-${Math.max(...markXs).toFixed(1)}`);
console.log(`Vector-2 (lockup): ${lockup.paths.length} paths, viewBox ${lockup.viewBox}, x range ${Math.min(...lockXs).toFixed(1)}-${Math.max(...lockXs).toFixed(1)}`);

// In the 122x28 lockup, the butterfly occupies roughly x < 33, the wordmark the rest.
const SPLIT_X = 33;
const butterflyPaths = lockup.paths.filter((p) => p.x < SPLIT_X);
const textPaths = lockup.paths.filter((p) => p.x >= SPLIT_X);
console.log(`Lockup split: ${butterflyPaths.length} butterfly paths, ${textPaths.length} wordmark paths`);

const esc = (s) => s.replace(/"/g, '\\"');
const pathEl = (p, fill) =>
  `      <path d="${esc(p.d)}"${p.evenodd ? ' fillRule="evenodd" clipRule="evenodd"' : ""} fill="${fill}" />`;

// Vector-2 is the wordmark alone (122x28); compose the lockup as
// butterfly (Vector-1, 60x40 scaled to 28 tall) + gap + wordmark.
const lockupBody = [
  `      {/* butterfly mark (from Vector-1) */}`,
  `      <g transform="scale(0.7)">`,
  ...mark.paths.map((p) => "  " + pathEl(p, ACCENT)),
  `      </g>`,
  `      {/* wordmark (from Vector-2) */}`,
  `      <g transform="translate(52 0)">`,
  ...lockup.paths.map((p) => "  " + pathEl(p, "currentColor")),
  `      </g>`,
].join("\n");

const tsx = `// GENERATED by scripts/prep-assets.mjs from assets/Vector-1.svg + assets/Vector-2.svg
// (official smalBlu deck exports, recolored). Do not edit by hand.

export function LogoMark({ className }: { className?: string }) {
  return (
    <svg viewBox="${mark.viewBox}" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
${mark.paths.map((p) => pathEl(p, "currentColor")).join("\n")}
    </svg>
  );
}

export function LogoLockup({ className, title = "smalBlu" }: { className?: string; title?: string }) {
  return (
    <svg viewBox="0 0 174 28" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} role="img" aria-label={title}>
${lockupBody}
    </svg>
  );
}
`;

mkdirSync(join(root, "components"), { recursive: true });
writeFileSync(join(root, "components", "logo.tsx"), tsx);
console.log("wrote components/logo.tsx");

// SVG favicon: blue butterfly on transparent, padded to a square viewBox.
const [, , w, h] = mark.viewBox.split(/\s+/).map(Number);
const size = Math.max(w, h);
const ox = (size - w) / 2;
const oy = (size - h) / 2;
const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}">
<g transform="translate(${ox} ${oy})">
${mark.paths.map((p) => `<path d="${p.d}"${p.evenodd ? ' fill-rule="evenodd" clip-rule="evenodd"' : ""} fill="${ACCENT}"/>`).join("\n")}
</g>
</svg>
`;
mkdirSync(join(root, "app"), { recursive: true });
writeFileSync(join(root, "app", "icon0.svg"), favicon);
console.log("wrote app/icon0.svg");
